version: '3'

services:
  web:
    container_name: node
    build:
        context: ./docker/node
    volumes:
    - ./:/usr/src/app
    ports:
      - "8000:3000"
        #working_dir: /usr/src/app
    stdin_open: true
    tty: true

